### ISSUE TITLE
failed xml -> md conversion with DAP4:Specification_Volume_1.xml

### ISSUE THREAD

**Issue by Mikejmnez** [Mikejmnez/wiki-files#2]
I ran

```unix
docker run -v $PWD:/app oooc/mediawiki-to-gfm --filename=OPeNDAP+Documentation-DAP4:Specification_Volume_1.xml
```
and got the following error:
```unix
Error at "/tmp/pandoc667e01a101017" (line 1362, column 4):
unexpected 'c'
{| class="wikitable
   ^
Pandoc\PandocException: Pandoc could not convert successfully, error code: 64. Tried to run the following command: /usr/bin/pandoc --from=mediawiki --to=gfm /tmp/pandoc667e01a101017 in /mediawiki-to-gfm/vendor/ryakad/pandoc-php/src/Pandoc/Pandoc.php:287
Stack trace:
#0 /mediawiki-to-gfm/app/src/Convert.php(194): Pandoc\Pandoc->runWith('[[Category:Deve...', Array)
#1 /mediawiki-to-gfm/app/src/Convert.php(149): App\Convert->runPandoc('[[Category:Deve...')
#2 /mediawiki-to-gfm/app/src/Convert.php(117): App\Convert->convertData()
#3 /mediawiki-to-gfm/convert.php(50): App\Convert->run()
#4 {main}
```

**Comment by Mikejmnez** [comment]
Same error with:

```
docker run -v $PWD:/app oooc/mediawiki-to-gfm --filename=OPeNDAP+Documentation-DAP4_Essential_Features.xml
```
