### ISSUE TITLE
failed xml -> md conversion with UserGuideDataModel.xml

### ISSUE THREAD

**Issue by Mikejmnez** [Mikejmnez/wiki-files#3]
I ran

```unix
docker run -v $PWD:/app oooc/mediawiki-to-gfm --filename=OPeNDAP+Documentation-UserGuideDataModel.xml
```
and got following error

```unix
Error at "/tmp/pandoc667e023e0796a" (line 660, column 1):
unexpected end of input
expecting white space
Pandoc\PandocException: Pandoc could not convert successfully, error code: 64. Tried to run the following command: /usr/bin/pandoc --from=mediawiki --to=gfm /tmp/pandoc667e023e0796a in /mediawiki-to-gfm/vendor/ryakad/pandoc-php/src/Pandoc/Pandoc.php:287
Stack trace:
#0 /mediawiki-to-gfm/app/src/Convert.php(194): Pandoc\Pandoc->runWith('[[UserGuide|Bac...', Array)
#1 /mediawiki-to-gfm/app/src/Convert.php(149): App\Convert->runPandoc('[[UserGuide|Bac...')
#2 /mediawiki-to-gfm/app/src/Convert.php(117): App\Convert->convertData()
#3 /mediawiki-to-gfm/convert.php(50): App\Convert->run()
#4 {main}
```

**Comment by Mikejmnez** [comment]
Same error with:

```unix
docker run -v $PWD:/app oooc/mediawiki-to-gfm --filename=OPeNDAP+Documentation-Wiki_Testing_OpeNDAP_Users_Guide.xml
```


```unix
docker run -v $PWD:/app oooc/mediawiki-to-gfm --filename=OPeNDAP+Documentation-Wiki_Testing_ServerInstallationGuidePreface.xml
```
